const STORAGE_KEYS={profile:'nhh.profile.v1',checks:'nhh.checks.v1',scheduler:'nhh.scheduler.v1'};
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday'];
const DAY_SHORT=['Mon','Tue','Wed','Thu','Fri'];
const START_MIN=7*60,END_MIN=17*60,SLOT_MIN=15;
let profile=loadJSON(STORAGE_KEYS.profile,{});
let checks=loadJSON(STORAGE_KEYS.checks,{});
let selectedTraining=0;
let scheduleState=loadJSON(STORAGE_KEYS.scheduler,{monthlyTarget:100,targetDays:20,events:[]});
function loadJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function saveJSON(key,value){localStorage.setItem(key,JSON.stringify(value))}
function byId(id){return document.getElementById(id)}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function time(min){const h24=Math.floor(min/60),m=min%60,s=h24>=12?'PM':'AM',h=((h24+11)%12)+1;return `${h}:${String(m).padStart(2,'0')} ${s}`}
function dur(min){const h=Math.floor(min/60),m=min%60;return h?`${h}h ${m?`${m}m`:''}`.trim():`${m}m`}
function name(){return profile.preferredName||profile.firstName||'Therapist'}
function slug(v=''){return String(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
function resourcePath(label){return `assets/resources/${slug(label)}`}
function initNavigation(){document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)))}
function showView(id){document.querySelectorAll('.nav-item').forEach(i=>i.classList.toggle('active',i.dataset.view===id));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id===id))}
function initSettings(){const d=byId('settingsDialog'),f=byId('profileForm');byId('openSettings').addEventListener('click',()=>{['firstName','preferredName','lastName','birthday','hireDate'].forEach(k=>{if(f.elements[k])f.elements[k].value=profile[k]||''});d.showModal()});f.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(f);const next={firstName:data.get('firstName')||'',preferredName:data.get('preferredName')||'',lastName:data.get('lastName')||'',birthday:data.get('birthday')||'',hireDate:data.get('hireDate')||'',photo:profile.photo||''};const photo=f.elements.photo.files[0];const save=()=>{profile=next;saveJSON(STORAGE_KEYS.profile,profile);renderAll();d.close()};if(photo){const r=new FileReader();r.onload=()=>{next.photo=r.result;save()};r.readAsDataURL(photo)}else save()});byId('clearProfile').addEventListener('click',()=>{profile={};saveJSON(STORAGE_KEYS.profile,profile);f.reset();renderAll()})}
function rampInfo(){const schedule=[0,25,50,75,75,100];if(!profile.hireDate)return{currentMonth:1,percentage:0,schedule};const hire=new Date(`${profile.hireDate}T00:00:00`),now=new Date();const diff=Math.max(0,(now.getFullYear()-hire.getFullYear())*12+now.getMonth()-hire.getMonth());const currentMonth=Math.min(6,diff+1);return{currentMonth,percentage:schedule[currentMonth-1],schedule}}
function renderHome(){const n=name(),r=rampInfo();byId('home').innerHTML=`<div class="hero"><div class="card"><div class="profile-strip">${profile.photo?`<img class="avatar" src="${profile.photo}" alt="Profile photo" />`:`<div class="avatar">${esc(n[0]||'T')}</div>`}<div><p class="eyebrow">School-Based Services</p><h2>Welcome, ${esc(n)}</h2><p>One clean desktop hub for onboarding, training, resources, and sustainable school-based practice.</p></div></div></div><div class="card"><p class="eyebrow">Current Ramp-Up</p><h3>Month ${r.currentMonth} · ${r.percentage}%</h3><div class="ramp-grid">${r.schedule.map((pct,i)=>`<div class="ramp-month ${i+1===r.currentMonth?'current':''}"><span>Month ${i+1}</span><strong>${pct}%</strong>${i===5?'<small>⭐ Incentive Eligible</small>':''}</div>`).join('')}</div></div></div><div class="section-grid"><div class="card"><p class="eyebrow">First month</p><h3>First 30 Days Checklist</h3><p>A simplified checklist that keeps the first month clear without opening a spreadsheet.</p><button class="primary-button" data-open-first30>Open Checklist</button></div><div class="card"><p class="eyebrow">Onboarding</p><h3>Start Here</h3>${HUB_DATA.onboarding.map(x=>`<p><strong>${esc(x.title)}</strong><br>${esc(x.summary)}</p>`).join('')}</div><div class="card full"><div class="header-row"><div><p class="eyebrow">Workflow</p><h3>Daily / Weekly / Monthly Checklist</h3></div></div><div class="check-tabs"><button class="tab-button active" data-check-tab="daily">Daily</button><button class="tab-button" data-check-tab="weekly">Weekly</button><button class="tab-button" data-check-tab="monthly">Monthly</button></div><div id="checklistPanel"></div></div></div>`;renderChecklist('daily')}
function checkRow(key,text){return`<label class="check-item"><input type="checkbox" data-check="${esc(key)}" ${checks[key]?'checked':''}/><span>${esc(text)}</span></label>`}
function renderChecklist(type){byId('checklistPanel').innerHTML=`<div class="checklist">${HUB_DATA.checklists[type].map((x,i)=>checkRow(`${type}.${i}`,x)).join('')}<label class="check-item"><input type="checkbox" data-check="${type}.other" ${checks[`${type}.other`]?'checked':''}/><span><strong>Other:</strong><input class="other-input" data-other="${type}" value="${esc(checks[`${type}.otherText`]||'')}" placeholder="Add your own ${type} item" /></span></label></div>`}
function renderWelcome(){const leaders=['Marion Smyser, LCSW','Topher Fuqua, LMFT','Anna Tukivakala-Holly, LPC-MHSP','Erin Edwards-Garrett, LMSW','Gabriella-Natasha Byers, LPC-MHSP','Karen Hasselman, LCSW','Kenya Dabney, LPC-MHSP','Tiffany Lester, LCSW'];byId('welcome').innerHTML=`<div class="card brand-hero"><p class="eyebrow">Welcome Center</p><h2>Delivering care that changes people’s lives.</h2><p>This section introduces the mission, role, program story, and people who support new school-based therapists.</p></div><div class="section-grid"><div class="card"><h3>About Centerstone</h3><p>Centerstone is a nonprofit health system specializing in mental health and substance use treatment. School-Based Services brings care into the educational ecosystem.</p><div class="resource-row"><button class="ghost-button">About Centerstone PDF</button><button class="ghost-button">Code of Conduct</button></div></div><div class="card"><h3>Our Reach</h3><p>Placement for the Tennessee School-Based Services map and district growth story.</p></div><div class="card full"><h3>Meet Your Leadership Team</h3><div class="leader-grid">${leaders.map(l=>`<div class="leader-card"><div class="dossier-photo">${l.split(' ').map(p=>p[0]).slice(0,2).join('')}</div><strong>${esc(l)}</strong><span>Leadership support profile</span></div>`).join('')}</div></div><div class="card"><h3>Day in the Life</h3><p>View-only placement for the Day in the Life PowerPoint.</p><button class="primary-button">Open Presentation</button></div><div class="card"><h3>Growing Together</h3><p>Team photos, welcome video, and program growth story belong here.</p></div></div>`}
function renderTraining(){const t=HUB_DATA.trainings[selectedTraining]||HUB_DATA.trainings[0];byId('training').innerHTML=`<div class="card training-hero"><div><p class="eyebrow">Training Dashboard</p><h2>Core Training Library</h2><p>Open each training page and launch the existing PowerPoints, PDFs, videos, and tools. No tracking. No completion boxes.</p></div><strong>${HUB_DATA.trainings.length} trainings</strong></div><div class="training-dashboard-grid page-gap"><div class="training-card-grid">${HUB_DATA.trainings.map((x,i)=>trainingCard(x,i)).join('')}</div><div id="trainingDetail" class="card training-detail-card"></div></div>`;renderTrainingDetail(t)}
function trainingCard(x,i){return`<button class="training-tile ${i===selectedTraining?'active':''}" data-training="${i}"><span class="training-number">${String(i+1).padStart(2,'0')}</span><strong>${esc(x.title)}</strong><small>${esc(x.trainer||'Trainer listed in training')}</small><em>${x.resources?.length||0} resources</em></button>`}
function resourceButton(label){return`<button class="ghost-button resource-launch" data-resource="${esc(resourcePath(label))}">${esc(label)}</button>`}
function renderTrainingDetail(t){byId('trainingDetail').innerHTML=`<p class="eyebrow">${esc(t.trainer||'Training')}</p><h2>${esc(t.title)}</h2><p class="training-description">${esc(t.purpose)}</p><div class="detail-section"><h3>Objectives</h3><ol class="objectives">${t.objectives.map(o=>`<li>${esc(o)}</li>`).join('')}</ol></div><div class="detail-section"><h3>Resources</h3><p class="resource-note">Buttons are wired as launchers for the matching files in the app resources folder.</p><div class="resource-row">${t.resources.map(resourceButton).join('')}</div></div>${t.id==='scheduling'?schedulerTemplate():''}`;if(t.id==='scheduling')initScheduler()}
function schedulerTemplate(){return`<div class="scheduler-card"><div class="scheduler-header"><div><p class="eyebrow">Scheduling for Success</p><h2>Scheduler Tool</h2><p>Productivity simulator for building a recurring school-based practice week.</p></div><button class="ghost-button" id="clearSchedule">Clear Week</button></div><div class="scheduler-controls"><label>Monthly Target<input id="monthlyTarget" type="number" min="0" step="0.01" /></label><label>School Days This Month<input id="targetDays" type="number" min="1" step="1" /></label><label>District Calendar<select id="calendarSelect"><option value="">Select district calendar</option>${HUB_DATA.calendars.map(c=>`<option value="${c.file}">${esc(c.label)}</option>`).join('')}</select></label></div><div class="planner-wrap"><div class="planner-grid" id="plannerGrid"></div></div><div class="clinical-summary" id="clinicalSummary"></div><div class="coaching-panel" id="coachingPanel"></div></div>`}
function initScheduler(){byId('monthlyTarget').value=scheduleState.monthlyTarget;byId('targetDays').value=scheduleState.targetDays;byId('monthlyTarget').addEventListener('input',syncSchedulerControls);byId('targetDays').addEventListener('input',syncSchedulerControls);byId('calendarSelect').addEventListener('change',e=>{if(e.target.value)window.open(e.target.value,'_blank')});byId('clearSchedule').addEventListener('click',()=>{scheduleState.events=[];persistScheduler();renderScheduler()});renderScheduler()}
function syncSchedulerControls(){scheduleState.monthlyTarget=Number(byId('monthlyTarget').value||0);scheduleState.targetDays=Math.max(1,Number(byId('targetDays').value||1));persistScheduler();renderScheduler()}
function persistScheduler(){saveJSON(STORAGE_KEYS.scheduler,scheduleState)}
function getType(id){return HUB_DATA.sessionTypes.find(t=>t.id===id)}
function dailyTarget(){return Number(scheduleState.monthlyTarget||0)/Math.max(1,Number(scheduleState.targetDays||1))}
function eventCredit(e){const t=getType(e.typeId);return t?(t.requiresParticipants?t.credit*Number(e.participants||0):t.credit):0}
function dayStats(i){const events=scheduleState.events.filter(e=>e.day===i);const totalTime=events.reduce((s,e)=>s+(getType(e.typeId)?.duration||0),0);const billable=events.reduce((s,e)=>s+eventCredit(e),0);const nonBillable=events.reduce((s,e)=>s+((getType(e.typeId)?.category!=='billable')?(getType(e.typeId)?.duration||0):0),0);const target=dailyTarget();return{events,totalTime,billable,nonBillable,target,remaining:Math.max(0,target-billable)}}
function renderScheduler(){const grid=byId('plannerGrid');if(!grid)return;const rows=[];for(let m=START_MIN;m<END_MIN;m+=SLOT_MIN)rows.push(m);grid.style.gridTemplateRows=`48px repeat(${rows.length},30px)`;grid.innerHTML=`<div class="planner-corner">Time</div>${DAY_SHORT.map(d=>`<div class="planner-day-head">${d}</div>`).join('')}`;rows.forEach(m=>{grid.insertAdjacentHTML('beforeend',`<div class="time-cell">${m%60===0?time(m):''}</div>`);DAYS.forEach((_,i)=>grid.insertAdjacentHTML('beforeend',`<button class="slot-cell" data-day="${i}" data-start="${m}"></button>`))});document.querySelectorAll('.slot-cell').forEach(c=>c.addEventListener('click',()=>openSessionModal(Number(c.dataset.day),Number(c.dataset.start))));scheduleState.events.forEach(renderEventBlock);renderSummary();renderCoaching()}
function renderEventBlock(e){const grid=byId('plannerGrid'),t=getType(e.typeId);if(!t)return;const startRow=2+Math.floor((e.start-START_MIN)/SLOT_MIN),span=Math.max(1,Math.ceil(t.duration/SLOT_MIN)),col=e.day+2;const b=document.createElement('button');b.className=`event-block ${t.category==='billable'?'billable':'nonbillable'}`;b.style.gridColumn=col;b.style.gridRow=`${startRow} / span ${span}`;b.innerHTML=`<strong>${esc(t.label)}</strong><span>${time(e.start)} · ${dur(t.duration)}</span><small>${t.category==='billable'?`${eventCredit(e).toFixed(2)} credits`:esc(e.adminTask||'0 credits')}</small>`;b.addEventListener('click',ev=>{ev.stopPropagation();openSessionModal(e.day,e.start,e.id)});grid.appendChild(b)}
function openSessionModal(day,start,id=null){const existing=id?scheduleState.events.find(e=>e.id===id):null;const modal=document.createElement('dialog');modal.className='settings-dialog';modal.innerHTML=`<form method="dialog" class="settings-card session-form"><div class="dialog-header"><div><p class="eyebrow">${DAYS[day]} · ${time(start)}</p><h2>${existing?'Edit Session':'Choose Session Time'}</h2></div><button class="icon-button" value="cancel">×</button></div><label>Session Type<select name="typeId">${HUB_DATA.sessionTypes.map(t=>`<option value="${t.id}" ${existing?.typeId===t.id?'selected':''}>${esc(t.label)}</option>`).join('')}</select></label><label class="participants-field">Participant Count<input name="participants" type="number" min="1" value="${existing?.participants||''}" /></label><label class="admin-field">Admin Activity<select name="adminTask"><option value="">Select activity</option>${HUB_DATA.adminTasks.map(a=>`<option ${existing?.adminTask===a?'selected':''}>${esc(a)}</option>`).join('')}</select></label><div class="dialog-actions">${existing?'<button type="button" class="ghost-button delete-session">Delete</button>':''}<button class="primary-button" value="default">Save Session</button></div></form>`;document.body.appendChild(modal);const form=modal.querySelector('form');const refresh=()=>{const t=getType(form.elements.typeId.value);modal.querySelector('.participants-field').style.display=t?.requiresParticipants?'grid':'none';modal.querySelector('.admin-field').style.display=t?.requiresAdminTask?'grid':'none'};form.elements.typeId.addEventListener('change',refresh);refresh();form.addEventListener('submit',ev=>{ev.preventDefault();const data=new FormData(form),t=getType(data.get('typeId'));if(t.requiresParticipants&&!Number(data.get('participants')))return alert('Participant count is required for group sessions.');const payload={id:existing?.id||crypto.randomUUID(),day,start,typeId:data.get('typeId'),participants:Number(data.get('participants')||0),adminTask:data.get('adminTask')||''};scheduleState.events=existing?scheduleState.events.map(e=>e.id===existing.id?payload:e):[...scheduleState.events,payload];persistScheduler();modal.close();modal.remove();renderScheduler()});const del=modal.querySelector('.delete-session');if(del)del.addEventListener('click',()=>{scheduleState.events=scheduleState.events.filter(e=>e.id!==existing.id);persistScheduler();modal.close();modal.remove();renderScheduler()});modal.addEventListener('close',()=>modal.remove(),{once:true});modal.showModal()}
function renderSummary(){const weekly=DAYS.reduce((s,_,i)=>s+dayStats(i).billable,0);byId('clinicalSummary').innerHTML=`<div class="summary-card month-overview"><strong>Weekly Practice Snapshot</strong><span>${weekly.toFixed(2)} credits scheduled</span><span>Daily target: ${dailyTarget().toFixed(2)}</span></div>${DAYS.map((d,i)=>{const s=dayStats(i);return`<div class="summary-card"><strong>${d}</strong><span>Total Time: ${dur(s.totalTime)}</span><span>Billable: ${s.billable.toFixed(2)}</span><span>Non-Billable: ${dur(s.nonBillable)}</span><span>Remaining Target: ${s.remaining.toFixed(2)}</span></div>`}).join('')}`}
function renderCoaching(){const messages=[];DAYS.forEach((d,i)=>{const s=dayStats(i);if(s.billable<s.target)messages.push(`${d}: add ${s.remaining.toFixed(2)} billable credits to meet the daily target.`);if(s.totalTime>480)messages.push(`${d}: scheduled time exceeds an 8-hour workday.`)});byId('coachingPanel').innerHTML=`<div class="card compact-card"><p class="eyebrow">Coaching Engine</p><h3>Scheduling Recommendations</h3>${messages.length?`<ul>${messages.slice(0,6).map(m=>`<li>${esc(m)}</li>`).join('')}</ul>`:'<p>Your current week is balanced against the entered target.</p>'}</div>`}
function showFirst30(){const modal=document.createElement('dialog');modal.className='settings-dialog';modal.innerHTML=`<form method="dialog" class="settings-card"><div class="dialog-header"><div><p class="eyebrow">First month</p><h2>First 30 Days Checklist</h2></div><button class="icon-button" value="cancel">×</button></div>${HUB_DATA.first30Days.map(sec=>`<details open><summary>${esc(sec.group)}</summary><div class="checklist">${sec.items.map((item,i)=>checkRow(`first30.${sec.group}.${i}`,item)).join('')}</div></details>`).join('')}</form>`;document.body.appendChild(modal);modal.addEventListener('change',e=>{if(e.target.matches('[data-check]')){checks[e.target.dataset.check]=e.target.checked;saveJSON(STORAGE_KEYS.checks,checks)}});modal.addEventListener('close',()=>modal.remove(),{once:true});modal.showModal()}
function bindDynamic(){document.addEventListener('click',e=>{if(e.target.matches('[data-check-tab]')){document.querySelectorAll('.tab-button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');renderChecklist(e.target.dataset.checkTab)}const tb=e.target.closest('[data-training]');if(tb){selectedTraining=Number(tb.dataset.training);renderTraining()}const rb=e.target.closest('[data-resource]');if(rb){window.open(rb.dataset.resource,'_blank')}if(e.target.matches('[data-open-first30]'))showFirst30()});document.addEventListener('change',e=>{if(e.target.matches('[data-check]')){checks[e.target.dataset.check]=e.target.checked;saveJSON(STORAGE_KEYS.checks,checks)}});document.addEventListener('input',e=>{if(e.target.matches('[data-other]')){checks[`${e.target.dataset.other}.otherText`]=e.target.value;saveJSON(STORAGE_KEYS.checks,checks)}})}
function renderAll(){renderHome();renderWelcome();renderTraining()}
initNavigation();initSettings();bindDynamic();renderAll();