window.HUB_DATA = {
  colors: {
    centerstoneBlue: '#347f8f', teal: '#6ab4aa', yellow: '#f2c35e', orange: '#dd9345', darkGray: '#3f3f3f', lightBlue: '#a6d8da', red: '#bf5a36', purple: '#6f385d'
  },
  checklists: {
    daily: [
      'Always PRIORITIZE PROVIDING CLIENTS CARE before any administrative task. Save administrative work for the end of the day.',
      'Complete 90-100% of clinical documentation (progress notes and care plans) collaboratively in session using Eleos as a note-taker. Confirm active PCP ROI is on file, then update the PCP Communication form the same time as the care plan update.',
      'Review your schedule for the upcoming day and adjust as needed.',
      'Remove your therapist hat at the end of the 8 hour workday.'
    ],
    weekly: [
      'Review your schedule to ensure high-risk and high-acuity clients are included and that you have enough sessions to meet your daily target. Share your schedule with your team lead during your weekly meeting.',
      'Check in with school contacts to assess school needs.',
      'Complete any assigned intakes in 45-60 minutes.',
      'Attend clinical supervision once weekly and update status in Avatar.',
      'Attend team meeting (aka administrative supervision) weekly and update status in Avatar.',
      'Submit time in Workday for Team Lead approval by noon every Friday.'
    ],
    monthly: [
      'Update school contact with pertinent information including referral communication, caseload list, any upcoming anticipated time off, and any appropriate additional information requested by the school.',
      'Collaborate with the navigator as needed for referral updates, expired paperwork, or difficult-to-reach families.',
      'Submit caseload count (per school, and telehealth — anyone not a student at one of your schools) to Team Lead in the first team meeting of the month.',
      'Complete all Relias trainings on or before due date.'
    ]
  },
  leadership: [
    { name: 'Marion Smyser, LCSW', title: 'Director of CCFT and School-Based Services, Tennessee Market, Upper Region', email: 'marion.smyser@centerstone.org', phone: 'Mobile: 615-785-3926 | Office: 615-460-4244', linkedIn: 'https://www.linkedin.com/in/marion-smyser-lcsw-22b7881a3/', bio: 'Marion is a fierce advocate for accessible mental health care and for the clinicians who provide it. Her leadership is grounded in humility, clarity, and a deep respect for the people doing the work every day. Marion values flexibility and models it, offering support that lifts people up without taking away their autonomy. Outside of work, Marion is intentional about balancing leadership and family life. She champions the same work-life sustainability she wants for every clinician, believing that healthy teams create healthier outcomes for clients.' },
    { name: 'Topher Fuqua, LMFT', title: 'Program Manager, School-Based Services, Davidson, Rutherford, and Wilson Counties', email: 'christopher.fuqua@centerstone.org', phone: 'Mobile: 615-674-0629', linkedIn: 'https://www.linkedin.com/in/topher-fuqua-lmft/', links: [{ label: 'Schedule a 30 minute meeting', url: 'https://scheduler.zoom.us/christopher-fuqua/administrative-oversight-non-clinical-thirty' }, { label: 'Schedule a 60 minute meeting', url: 'https://scheduler.zoom.us/christopher-fuqua/administrative-oversight-non-clinical-hour' }], bio: 'Topher brings a systems-focused, collaborative approach to leadership and believes deeply in creating environments where teams feel supported, seen, and able to do their best work. Outside of work, he is usually experimenting with new creative outlets or in the garden with his hands in the dirt, a grounding practice that mirrors the slow, steady growth he values in people and programs alike. Topher’s professional goal is our program and teams sustainable growth; growth that strengthens the program without outpacing the people who make the work possible.' },
    { name: 'Anna Tukivakala-Holly, LPC-MHSP', title: 'Team Lead, Clinical Supervisor — LSSD, Wilson County', email: 'anna.tukivakala-holly@centerstone.org', phone: '615-210-9324', bio: 'Anna serves as the team lead for Lebanon Special School District and Wilson County Schools, as well as providing licensure supervision for professional counselors.' },
    { name: 'Erin Edwards-Garrett, LMSW', title: 'Team Lead — MCS, Rutherford County', email: 'erin.edwards@centerstone.org', phone: '629-395-6982', bio: 'Erin is entering her fifth school year with our program and is helping expand our footprint in Rutherford County. In 2025-26 Erin represented and advocated for our program, serving on Centerstone’s Work Voices Committee. A self-proclaimed nerd, Erin models healthy self-care through hobbies like diamond art and engages in professional growth through listening to Geek Therapy podcasts.' },
    { name: 'Gabriella-Natasha Byers, LPC-MHSP', title: 'Team Lead — Davidson County', email: 'GabriellaNatasha.Byers@centerstone.org', phone: '629-203-4996', linkedIn: 'https://www.linkedin.com/in/gabriella-natasha-byers-7164a942/', bio: 'Gabriella-Natasha “Gabi” Byers is a champion for equality, fairness, and consistency in the workplace. She leads with clarity, compassion, and purpose—setting expectations that help her team thrive. Gabi believes healing happens not just in hours but in transformative moments, creating space for growth and grace.' },
    { name: 'Karen Hasselman, LCSW', title: 'Team Lead, Clinical Supervisor — Davidson County', email: 'karen.hasselman@centerstone.org', phone: '615-684-5067', linkedIn: 'https://www.linkedin.com/in/khasselman-lmsw/', links: [{ label: 'Featured Article', url: 'https://centerstone.org/our-resources/health-wellness/school-based-therapy-is-helpful-to-children/' }], bio: 'Karen provides consistent guidance to help clinicians navigate the fast-paced realities of school-based work while maintaining high standards of care and service delivery. She fosters open communication, encourages autonomy, and challenges team members to exceed their expectations in ways that work for them.' },
    { name: 'Kenya Dabney, LPC-MHSP', title: 'Team Lead — Davidson County', email: 'kenya.dabney@centerstone.org', phone: '615-626-1930', linkedIn: 'https://www.linkedin.com/in/kenya-dabney-lpc-mhsp-4bb342135/', bio: 'Kenya leads with empathy, integrity, and a deep commitment to the well-being of her staff. She creates a safe, inclusive environment where team members feel valued, heard, and empowered to grow.' },
    { name: 'Tiffany Lester, LCSW', title: 'Team Lead, Clinical Supervisor — Rutherford County', email: 'tiffany.lester@centerstone.org', phone: '615-970-0781', links: [{ label: 'Schedule a 60-Minute Meeting', url: 'https://scheduler.zoom.us/tiffany-lester/admin-page' }], bio: 'Tiffany leads with collaboration, consistency, and clear communication. She supports clinicians with a steady, trauma-informed approach and works to remove barriers so teams can focus on caring for students and families. She cares deeply about reducing burnout, building resiliency, and creating a healthy, supportive team culture.' }
  ],
  trainings: [
    { title: 'Avatar: Basic Navigation', trainer: 'Anna Tukivakala-Holly, LPC-MHSP and Tiffany Lester, LCSW', purpose: 'Foundational training to introduce the electronic health record and paperwork required for client care.', objectives: ['Use the school-based bundle correctly', 'Identify and describe each required client form', 'Complete all three types of cancellations', 'Navigate between Avatar test system and Avatar live', 'Schedule an intake assessment and apply Eleos from the first session'], homework: 'Practice the new client workflow using the provided referral form.', resources: ['Avatar Basic Navigation PowerPoint', 'School-Based Fillable Forms Packet'] },
    { title: 'Scheduling for Success', trainer: 'Topher Fuqua, LMFT', purpose: 'Explore how budget works, why sustainable scheduling protects both therapist and client, and practical strategies that support consistent target achievement without burnout.', objectives: ['Understand the significance of the budget and how it connects to mission', 'Prioritize necessary work tasks while maintaining work-life balance', 'Learn strategies to manage time and hit target consistently', 'Learn how to be strategic when scheduling'], homework: 'Add recurring team meeting and clinical supervision to your Avatar schedule through January.', resources: ['Scheduling for Success PowerPoint', 'Scheduler Tool'] },
    { title: 'Relationship Building', trainer: 'Erin Edwards-Garrett, LMSW', purpose: 'Focus on how intentional, consistent relationships support effective clinical work and strengthen outcomes across school, family, and team systems.', objectives: ['Recognize relationship building as a foundational clinical skill', 'Identify practices that strengthen relationships', 'Reflect on consistency, boundaries, and follow through', 'Practice perspective-taking and relational decision-making', 'Identify one relational practice to apply'], homework: 'Update one template or create a similarly styled service flyer.', resources: ['Building Relationships PowerPoint', 'Service Flyer Templates'] },
    { title: 'Telehealth 101', trainer: 'Gabriella-Natasha Byers, LPC-MHSP', purpose: 'Explore effective, ethical, and engaging telehealth service delivery.', objectives: ['Describe clinical and practical benefits', 'Apply Centerstone telehealth policies', 'Document telehealth accurately in Avatar', 'Navigate Zoom and technology smoothly', 'Access telehealth therapeutic activities and resources'], homework: 'Bookmark 3 go-to interventions or therapeutic activities.', resources: ['Telehealth 101 PowerPoint', 'Telehealth Procedures', 'Telehealth Toybox'] },
    { title: 'Diagnosing with Confidence', trainer: 'Karen Hasselman, LCSW', purpose: 'Build confidence around diagnosis in a school-based setting.', objectives: ['Access the online DSM-5-TR', 'Use diagnostic reasoning with confidence', 'Apply assessments to inform diagnosis', 'Understand and apply Z-codes', 'Explain EOC and how it applies to ADHD and ODD'], homework: 'Review at least one assigned client chart and staff in clinical supervision.', resources: ['Diagnosing with Confidence PowerPoint', 'Guess Who DSM-5 Edition', 'DSM V Simplified'] },
    { title: 'Prevention Pathways Overview', trainer: 'Anna Tukivakala-Holly, LPC-MHSP and Karen Hasselman, LCSW', purpose: 'Build confidence with suicide prevention and violence risk pathways.', objectives: ['Identify the three clinical pathways', 'Administer, score, and interpret assessments', 'Apply enrollment and disenrollment criteria', 'Use the Stanley-Brown safety plan, safety sweep, and CALM', 'Describe the RELATE model'], homework: 'Explore Now Matters Now and download an SBSP app.', resources: ['Prevention Pathways PowerPoint', 'Stanley Brown Safety Plan', 'Safety Sweep Checklist'] },
    { title: 'Eleos: Putting it into Practice', trainer: 'Kenya Dabney, LPC-MHSP', purpose: 'Use Eleos as a note-taker so documentation can be completed before the client leaves.', objectives: ['Explain what Eleos captures', 'Log in to Eleos', 'Set up Eleos mobile', 'Use Eleos from start to finish in session', 'Map Eleos outputs to note template'], homework: 'Practice introducing Eleos to a peer as if introducing it to a parent.', resources: ['Eleos PowerPoint', 'Using Eleos Guide'] },
    { title: 'Starting a School-Based Group', trainer: 'Topher Fuqua, LMFT', purpose: 'Move from “I should start a group” to “my first group is running.”', objectives: ['Explain why group therapy is effective', 'Design an appropriate group', 'Create an implementation plan', 'Complete consent, care plan, and Avatar requirements', 'Launch and facilitate with confidence'], homework: 'Reach out and get consent for 6-8 clients and add consent as a memo to chart.', resources: ['Starting a School-Based Group PowerPoint'] },
    { title: 'New Hire Group', trainer: 'Tiffany Lester, LCSW', purpose: 'Weekly support through guided topics, peer discussion, and facilitator-led problem solving.', objectives: ['Welcome and connection', 'Self-care and compassion fatigue', 'Email mastery and workflow', 'Measurement based care', 'Parent engagement', 'Crisis and school protocols', 'Intervention exchange', 'Benefits and growth'], homework: 'Use the discussion notes pages and complete assigned reminders.', resources: ['New Hire Group Rotatable PowerPoint', 'Workbook'] },
    { title: 'Ecosystem Workbook', trainer: 'Self-paced with Team Lead discussion', purpose: 'Introduces new hires to the school-based setting before stepping into schools.', objectives: ['Role clarity', 'Scheduling and priorities', 'Targets, time, and energy budget', 'Documentation habits', 'School culture and crisis cues', 'Boundaries and sustainable pacing'], homework: 'Complete workbook sections during first two weeks.', resources: ['Field Guide to the School-Based Ecosystem'] }
  ],
  calendars: [
    { label: 'Metro Nashville Public Schools', url: 'https://resources.finalsite.net/images/v1772556285/mnpsorg/mnpsorg/evnn2p4puxpvncbtojm5/MNPSDistrictCalendar2026-2027_English_updated02092026.pdf' },
    { label: 'Murfreesboro City Schools', url: 'https://resources.finalsite.net/images/v1775835497/cityschoolsnet/iomdoih1pjalvwrt6ln7/2026-27-MCS-School-Calendar.pdf' },
    { label: 'Rutherford County Schools', url: 'https://files-backend.assets.thrillshare.com/documents/asset/uploaded_file/5892/Rcs/9bb22603-fc72-4ccb-84d9-c323a8730a22/2026-2027-RCSAcademicCalendar-v02.docx?disposition=inline' },
    { label: 'Lebanon Special School District', url: 'https://4.files.edl.io/aadb/11/22/24/201347-18f45683-53e6-46d5-bc34-9005b02841ad.pdf' },
    { label: 'Wilson County Schools', url: 'https://www.wcschools.com/calendar/#docaccess-31b3ad362aa71877e59dbb04698fe2fa' }
  ]
};
